name = "andy-burnham-yet"
main = "src/worker.js"
compatibility_date = "2026-06-23"

[assets]
directory = "./public"

[[kv_namespaces]]
binding = "COMMENTARY_CACHE"
id = "c2d82888344c4c6897d04993eb08733a"

[triggers]
crons = ["0 */6 * * *"]
